In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Customer_analysis.csv')
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
...,...,...,...,...,...,...,...,...,...,...
401599,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,2011-12
401600,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,2011-12
401601,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12
401602,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,2011-12
401603,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,2011-12

***RFM Analysis***
R - Recency means How recently did customer buy?
F - Frequency means How often do they buy?
M - Monetary means How much do they spend?

In [6]:
# Calculate Recency
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
snapshot_date = df['InvoiceDate'].max() + pd.Timedelta(days=1)
rfm = df.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'nunique',
    'TotalPrice': 'sum'
})
rfm.columns = ['Recency', 'Frequency', 'Monetary']
rfm

            Recency  Frequency  Monetary
CustomerID
12346.0         326          2      0.00
12347.0           2          7   4310.00
12348.0          75          4   1797.24
12349.0          19          1   1757.55
12350.0         310          1    334.40
...             ...        ...       ...
18280.0         278          1    180.60
18281.0         181          1     80.82
18282.0           8          3    176.60
18283.0           4         16   2045.53
18287.0          43          3   1837.28

[4372 rows x 3 columns]

In [7]:
#RFM Scoring
rfm['R_score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])
rfm['F_score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['M_score'] = pd.qcut(rfm['Monetary'], 4, labels=[1,2,3,4])
rfm

            Recency  Frequency  Monetary R_score F_score M_score
CustomerID
12346.0         326          2      0.00       1       2       1
12347.0           2          7   4310.00       4       4       4
12348.0          75          4   1797.24       2       3       4
12349.0          19          1   1757.55       3       1       4
12350.0         310          1    334.40       1       1       2
...             ...        ...       ...     ...     ...     ...
18280.0         278          1    180.60       1       2       1
18281.0         181          1     80.82       1       2       1
18282.0           8          3    176.60       4       3       1
18283.0           4         16   2045.53       4       4       4
18287.0          43          3   1837.28       3       3       4

[4372 rows x 6 columns]

In [8]:
rfm['RFM_Score'] = (
    rfm['R_score'].astype(str) +
    rfm['F_score'].astype(str) +
    rfm['M_score'].astype(str)
)
rfm

            Recency  Frequency  Monetary R_score F_score M_score RFM_Score
CustomerID
12346.0         326          2      0.00       1       2       1       121
12347.0           2          7   4310.00       4       4       4       444
12348.0          75          4   1797.24       2       3       4       234
12349.0          19          1   1757.55       3       1       4       314
12350.0         310          1    334.40       1       1       2       112
...             ...        ...       ...     ...     ...     ...       ...
18280.0         278          1    180.60       1       2       1       121
18281.0         181          1     80.82       1       2       1       121
18282.0           8          3    176.60       4       3       1       431
18283.0           4         16   2045.53       4       4       4       444
18287.0          43          3   1837.28       3       3       4       334

[4372 rows x 7 columns]

| RFM Condition          | Segment         |
| ---------------------- | --------------- |
| R high, F high, M high | Champions       |
| F high                 | Loyal Customers |
| R high, F low          | New Customers   |
| R low, F high          | At Risk         |
| Low everything         | Lost            |
| Others                 | Regular         |

In [9]:
def segment_customer(row):
    if row['R_score'] == 4 and row['F_score'] == 4:
        return 'Champions'
    elif row['F_score'] >= 3:
        return 'Loyal Customers'
    elif row['R_score'] == 4:
        return 'New Customers'
    elif row['R_score'] <= 2 and row['F_score'] >= 3:
        return 'At Risk'
    elif row['R_score'] == 1 and row['F_score'] == 1:
        return 'Lost Customers'
    else:
        return 'Regular Customers'

rfm['Segment'] = rfm.apply(segment_customer, axis=1)

In [10]:
rfm['Segment'].value_counts()

Segment
Loyal Customers      1580
Regular Customers    1430
Champions             606
Lost Customers        518
New Customers         238
Name: count, dtype: int64

In [11]:
rfm.to_csv("rfm_customer_segments.csv")